#!/bin/sh
export AUTH0_DOMAIN="your AUTH0 DOMAIN"
export ALGORITHMS="ALGORITHMS"
export API_AUDIENCE="your api audience"
export DATABASE_URL=""
export DATABASE_USER="your user"
export DATABASE_PASSWORD="your password"
export FLASK_APP="app.py"
export ASSISTANT_TOKEN=""
export PRODUCER_TOKEN=""
